<?xml version="1.0"?>
<package format="3">
  <name>planner</name>
  <version>0.0.0</version>
  <description>Wrapper de nós do stack ego-planner -> Raptor (conversão de odometria, ponte pos_cmd -> PX4 e utilitários de teste)</description>

  <maintainer email="voce@email.com">Seu Nome</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>quadrotor_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
